# Generated by Django 5.1.1 on 2024-09-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiography',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='radiography',
            name='desease',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
