# Generated by Django 5.1.1 on 2024-10-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_doctor_patient_radiographydiagnosis_radiographyimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_dni', models.CharField(max_length=10)),
                ('doctor_name', models.CharField(max_length=100)),
                ('disease', models.CharField(default='Unknown', max_length=100)),
                ('prediccion_probabilidad', models.FloatField()),
                ('prediccion_confianza', models.FloatField()),
                ('prediccion_entropia', models.FloatField()),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='radiographies/')),
            ],
        ),
        migrations.RemoveField(
            model_name='radiographydiagnosis',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='radiographydiagnosis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='radiographydiagnosis',
            name='radiography_image',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='RadiographyDiagnosis',
        ),
        migrations.DeleteModel(
            name='RadiographyImage',
        ),
    ]
